filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/*.log

output.logstash:
  hosts: ["logstash:5044"]
  timeout: 60
  slow_start: true

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
